name: CI

on:
  push:
    branches: [ master ]

jobs:
  # Run basic tests.
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: 12.18.3
      - name: Install Packages
        run: yarn install
      - name: Run Tests
        run: yarn test
      
  # Build artifacts if tests run successfully.
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: 12.18.3
      - name: Install Packages
        run: yarn install 
      - name: Build Artifacts
        run: yarn build
