name: Build and Push to DockerHub

on:
  push:
    branches: master

jobs:
  # Run basic tests.
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code and run tests.
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: 12.18.3
      - name: Install Packages
        run: yarn install
      - name: Run Tests
        run: yarn test

      # Setup environment for docker.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push image to DockerHub.
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          API_URL: ${{ secrets.MUJIK_API_URL }}
        with:
          push: true
          tags: ${{ secrets.MUJIK_WEB_TAG }}
          build-args: |
            API_URL=${{ secrets.MUJIK_API_URL }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
